name: Prolog Test

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/devel -y
        sudo apt-get update -q
        sudo apt-get install swi-prolog-nox

    - name: Run test
      run: swipl -s test_rutas.pl -g run_tests,halt -t 'halt(1)'
