name: Prolog Test

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/devel -y
        sudo apt-get update -q
        sudo apt-get install swi-prolog-nox

    # Runs a set of commands using the runners shell
    - name: Run test
      run: swipl -s test_rutas.pl -g run_tests,halt -t 'halt(1)'
