name: Prolog Test

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install swipl image
      run: docker pull swipl

    - name: Run test
      run: docker run -v $(pwd):/app swipl swipl -s app/test_rutas.pl -g run_tests
